#!/usr/bin/env node

const fs = require("fs");

const commitMsgFile = process.argv[2];
const commitMsg = fs.readFileSync(commitMsgFile, "utf8").trim();

// Regex to match the required format
const regex = /^ASTONJS-\d+ \[(feat|fix|chore)\]: [A-Za-z\s\-_\.,]+$/;

if (!regex.test(commitMsg)) {
  console.error(
    "Error: Commit message must follow the format: 'ASTONJS-<number> [feat/fix/chore]: <message>'"
  );
  process.exit(1);
}

process.exit(0);
